# Generated by Django 4.1.5 on 2023-01-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_multipleimage_delete_berra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
